### ISSUE TITLE
Create Service Icons

### ISSUE THREAD

**Issue by sherretten** [ewb-psu/shelter-project#16]
## Description
The mockup will need SVG icons which can represent services provided by different groups. These services will include finance, housing, food, and medical services.

## Acceptance Criteria
SVGs added to the project resources for services such as
- [x] Finance
- [x] Housing
- [x] Food
- [x] Medical

**Comment by emh221** [comment]
This is completed. The code for it is in the 4-SVG-for-Exclusive-option branch.
