### ISSUE TITLE
Select a Database

### ISSUE THREAD

**Issue by TrevorLeake** [ewb-psu/shelter-project#4]
Though the project is a bit amorphous right now, we have some idea of what data we'll be handling. Elements like
- Shelter/service name
- Hours of operation
- Location

However, all homeless services will vary in what attributes they have (e.g. a bed count will be great for night shelters, but won't make sense for day shelters). As well, the types of resources offered may get fairly specialized and case-to-case (such as food, showers, clothing, dental exams, vision exams, financial planning classes, etc.). We would probably prefer not to update the schema to include a new column every time we discover a new resource.

The project *may* need something beyond a relational database. Maybe document based, maybe graph based, etc. 

The project needs...
- A short document listing what data we'll likely care about
- An informal proposal as to which database we should use and why

Once these are in, we can greenlight it and start creating our schema and tables. :rainbow:

**Comment by seanlesch** [comment]
I think a document-based implementation may be the way to go. A relational DB will need tons of columns for booleans for if shelters have a service. A document-based DB could then just have values for services for each shelter. I would propose mongoDB, which has a free, open-source community repo and is pretty widely used.

**Comment by TrevorLeake** [comment]
Well, the course of the project changed a lot. We no longer need to create our own database, we'll use 211's backend. 

COMPLETE
