### ISSUE TITLE
County Validation

### ISSUE THREAD

**Issue by TrevorLeake** [ewb-psu/shelter-project#41]
## Description
When we enter a county into the `FieldSelector` component, the `countyValidator` function is run. We currently return `true` for entries of "Multnomah" or "Clackamas" and false otherwise. 

To improve on this, two obvious options are API integration and hard-coding. It appears that the [US Census Bureau](https://www.census.gov/data/developers/data-sets.html) has APIs which may be able to list the counties of a state. This would let us check if an entered county is valid.

We can also hardcode the counties and try to make it easy for 211 to change this hardcoding. 

Both paths have pros and cons; just do what's reasonable. :)

**Comment by emh221** [comment]
I am working on this. The progress that I have will be pushed to the branch county-validator shortly if someone else wants to look at it for the cors error thing. I have set two environmental api keys in order for this to work so checkout the readme. PLEASE NOTE IT HAS A BUG IN VALIDATION THAT IS STILL BEING WORKED ON.
