### ISSUE TITLE
Research what testing framework to use.

### ISSUE THREAD

**Issue by BrianDavidAllen** [ewb-psu/shelter-project#82]
## Description 
We need to decide what testing framework to use. So far, we're looking at Jest and Cyprus. We are open to any that fit our use case the best. 

## Requirments 
- [ ] Must be able to test API, DOM, and our functions in general.
- [ ] Must support all browsers

**Comment by Funkh0user** [comment]
Well, cypress is really great to use, but it doesn't support Safari or IE, and firefox support is in beta. Looks like jest wins.
